

# industry_keywords = {
#     "Agriculture": ["Farming", "Agricultural", "Harvest"],
#     "Fishing": ["Fishing", "Seafood", "Fisheries"],
#     "Forestry": ["Forestry", "Trees", "Wood", "Forest"],
#     "Mining and Quarrying": ["Mining", "Quarry"],
#     "Manufacturing": ["Manufacturing","Factory", "Industrial", "Machinery"],
#     "Automotive": ["Automotive", "Car", "Vehicle", "Motor", "Automobile"],
#     "Chemical": ["Chemicals", "Chemical", "Pharmaceutical", "Chemical Plant"],
#     "Electronics": ["Electronics", "Electronic", "Circuit"],
#     "Food and Beverage": ["Food", "Beverages", "Drinks", "Restaurant", "Dining", "Catering"],
#     "Pharmaceuticals": ["Drug", "Medicine", "Pharma", "Biotech", "Pharmaceutical", "Healthcare"],
#     "Textiles and Apparel": ["Textile", "Clothing", "Fashion", "Apparel", "Garments", "Textiles"],
#     "Construction": ["Construction", "Building", "Architecture", "Infrastructure", "Contractor"],
#     "Electricity Generation": ["Electricity", "Power Generation", "Energy", "Solar"],
#     "Gas Supply": ["Gas", "Natural Gas"],
#     "Water Supply": ["Water", "Drinking Water", "Hydrology"],
#     "Retail": ["Retail", "Shopping", "Store", "Consumer", "Market", "E-Commerce"],
#     "Healthcare": ["Hospital", "Medical", "Clinic", "Healthcare", "Doctor", "Nursing", "Pharmacy"],
#     "Education": ["Education", "School", "University", "Learning", "Academy", "Training"],
#     "Hospitality and Tourism": ["Tourism", "Hotel", "Travel", "Resort", "Vacation", "Hospitality", "Tourist"],
#     "Entertainment and Media": ["Entertainment", "Media", "Music", "Film", "Television", "Broadcast", "Streaming"],
#     "Financial Services": ["Finance", "Financial", "Banking", "Investment", "Capital", "Credit", "Accounting", "Bank"],
#     "Real Estate": ["Property", "Housing", "Real Estate", "Estate", "Land", "Brokerage"],
#     "Information Technology (IT) and Software Development": ["Software", "Digital", "Technology", "Information Technology"],
#     "Telecommunications": ["Telecom", "Communication", "Network", "Mobile", "Broadband"],
#     "Logistics and Transportation": ["Logistics", "Transportation", "Shipping", "Delivery"],
#     "Construction Materials": ["Construction Materials", "Building Materials", "Cement", "Bricks", "Steel"],
#     "Waste Management": ["Waste", "Recycling", "Disposal", "Sustainability"],
#     "Cybersecurity": ["Cybersecurity", "Security", "Data Protection", "Information Security"],
#     "Artificial Intelligence": ["Artificial Intelligence", "Machine Learning", "Deep Learning"],
#     "Blockchain": ["Blockchain", "Cryptocurrency"],
#     "Renewable Energy": ["Renewable Energy", "Renewable"],
#     "Aerospace": ["Aerospace", "Aircraft", "Space"],
#     "Biotechnology": ["Biotechnology", "Genetics", "Bioengineering", "Life Sciences"],
#     "Insurance": ["Insurance", "Insurance Policy", "Risk Management"],
#     "Non-Profit": ["Non-Profit", "Charity", "NGO", "Philanthropy"],
#     "2/3 Wheelers": ["Motorcycle", "Scooter", "Two-Wheeler"],
#     "Abrasives & Bearings": ["Abrasives", "Bearings"],
#     "Advertising & Media Agencies": ["Advertising", "Media", "Marketing"],
#     "Aerospace & Defense": ["Aerospace", "Defense", "Military"],
#     "Airline": ["Airline", "Aviation", "Flights"],
#     "Airport & Airport Services": ["Airport", "Airport Services"],
#     "Aluminium": ["Aluminium"],
#     "Aluminium, Copper & Zinc Products": ["Aluminium", "Copper", "Zinc"],
#     "Amusement Parks/ Other Recreation": ["Amusement", "Recreation"],
#     "Animal Feed": ["Animal Feed"],
#     "Asset Management Company": ["Asset Management", "Investment", "Finance"],
#     "Auto Components & Equipments": ["Auto Parts", "Components", "Vehicles"],
#     "Auto-Dealer": ["Auto Dealer", "Car Sales", "Automotive"],
#     "Breweries & Distilleries": ["Breweries", "Distilleries", "Alcohol"],
#     "Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)": ["BPO", "KPO", "Outsourcing"],
#     "Cables - Electricals": ["Cables", "Electrical", "Wiring"],
#     "Castings & Forgings": ["Castings", "Forgings", "Metalworking"],
#     "Cement & Cement Products": ["Cement", "Building Materials"],
#     "Ceramics": ["Ceramics", "Pottery", "Tiles"],
#     "Cigarettes & Tobacco Products": ["Cigarettes", "Tobacco", "Smoking"],
#     "Civil Construction": ["Civil Construction", "Infrastructure", "Building"],
#     "Coal": ["Coal", "Mining"],
#     "Commercial Vehicles": ["Commercial Vehicles", "Trucks", "Transportation"],
#     "Commodity Chemicals": ["Commodity Chemicals", "Industrial Chemicals"],
#     "Compressors, Pumps & Diesel Engines": ["Compressors", "Pumps", "Diesel"],
#     "Computers - Software & Consulting": ["Computers", "Consulting"],
#     "Computers Hardware & Equipments": ["Hardware", "Computers", "Equipment"],
#     "Construction Vehicles": ["Construction Vehicles", "Heavy Machinery"],
#     "Consulting Services": ["Consulting", "Advisory"],
#     "Consumer Electronics": ["Consumer Electronics", "Gadgets", "Electronics Devices"],
#     "Copper": ["Copper"],
#     "Dairy Products": ["Dairy", "Milk", "Cheese"],
#     "Data Processing Services": ["Data Processing", "Analytics", "IT Services"],
#     "Depositories, Clearing Houses and Other Intermediaries": ["Depositories", "Clearing Houses", "Finance"],
#     "Digital Entertainment": ["Digital Entertainment", "Streaming", "Media"],
#     "Distributors": ["Distributors", "Wholesale", "Supply Chain"],
#     "Diversified": ["Diversified", "Varied", "Multiple Sectors"],
#     "Diversified Commercial Services": ["Commercial Services", "Business Services"],
#     "Diversified Consumer Products": ["Consumer Products", "Diversified"],
#     "Diversified FMCG": ["FMCG", "Fast-Moving Consumer Goods"],
#     "Diversified Metals": ["Metals", "Diversified", "Mining"],
#     "Diversified Retail": ["Diversified Retail", "Diversified"],
#     "Dredging": ["Dredging"],
#     "Dyes And Pigments": ["Dyes", "Pigments"],
#     "Edible Oil": ["Edible Oil", "Cooking Oil"],
#     "Education": ["Education", "Learning", "Training"],
#     "E-Learning": ["E-Learning", "Online Education", "Digital Learning"],
#     "Electrodes & Refractories": ["Electrodes", "Refractories"],
#     "Electronic Media": ["Electronic Media", "Broadcasting", "Digital"],
#     "E-Retail/ E-Commerce": ["E-Retail", "E-Commerce", "Online Shopping"],
#     "Exchange and Data Platform": ["Exchange and Data Platform", "Data Platform"],
#     "Explosives": ["Explosives"],
#     "Ferro & Silica Manganese": ["Ferro", "Silica", "Manganese"],
#     "Fertilizers": ["Fertilizers", "Agriculture", "Crop"],
#     "Film Production, Distribution & Exhibition": ["Film", "Film Production",],
#     "Financial Institution": ["Financial Institution", "Banking", "Finance"],
#     "Financial Products Distributor": ["Financial Products", "Distribution"],
#     "Financial Technology (Fintech)": ["Python Financial Technology", "Fintech", "Digital Finance"],
#     "Footwear": ["Footwear", "Shoes"],
#     "Forest Products": ["Forest Products", "Wood", "Timber"],
#     "Furniture, Home Furnishing": ["Furniture", "Home Decor", "Interior"],
#     "Furniture, Home Furnishing, Flooring": ["Furniture", "Flooring", "Home"],
#     "Garments & Apparels": ["Garments", "Apparel", "Clothing"],
#     "Gas Transmission/Marketing": ["Gas Transmission", "Marketing", "Energy"],
#     "Gems, Jewellery And Watches": ["Gems", "Jewellery", "Watches"],
#     "General Insurance": ["Insurance"],
#     "Glass - Consumer": ["Glass", "Consumer Products", "Household"],
#     "Glass - Industrial": ["Glass", "Industrial Products"],
#     "Granites & Marbles": ["Granite", "Marble", "Stone"],
#     "Healthcare Research, Analytics & Technology": ["Healthcare"],
#     "Healthcare Service Provider": ["Healthcare Service", "Healthcare Service Provider"],
#     "Heavy Electrical Equipment": ["Heavy Equipment","Heavy Electrical Equipment"],
#     "Holding Company": ["Holding Company", "Investment", "Finance"],
#     "Hospital": ["Hospital", "Healthcare", "Medical"],
#     "Hotels & Resorts": ["Hotels", "Resorts", "Hospitality"],
#     "Household Appliances": ["Appliances", "Household"],
#     "Household Products": ["Household", "Cleaning"],
#     "Houseware": ["Houseware", "Kitchenware", "Home"],
#     "Housing Finance Company": ["Housing Finance", "Loans", "Mortgage"],
#     "Industrial Gases": ["Industrial Gases"],
#     "Industrial Machinery": ["Industrial Machinery"],
#     "Industrial Minerals": ["Industrial Minerals"],
#     "Industrial Products": ["Industrial Products"],
#     "Integrated Power Utilities": ["Power Utilities"],
#     "Internet & Catalogue Retail": ["Internet Retail", "Catalogue", "E-Commerce"],
#     "Investment Company": ["Investment", "Finance", "Portfolio"],
#     "Iron & Steel": ["Iron", "Steel", "Metals"],
#     "Iron & Steel Products": ["Iron Products", "Steel Products"],
#     "IT Enabled Services": ["IT Services", "Technology"],
#     "Jute & Jute Products": ["Jute", "Products"],
#     "Lamps & Lightings": ["Lamps", "Lighting", "Home Decor"],
#     "Landscaping": ["Landscaping", "Gardening", "Design"],
#     "Leather": ["Leather"],
#     "Leisure & Hospitality": ["Leisure", "Hospitality"],
#     "Life Sciences": ["Life Sciences", "Biotechnology"],
#     "Logistics": ["Logistics", "Transportation", "Shipping"],
#     "Lubricants & Oils": ["Lubricants", "Oils", "Chemicals"],
#     "Machinery": ["Machinery", "Equipment"],
#     "Marine": ["Marine", "Shipping", "Waterways"],
#     "Market Research": ["Market Research", "Surveys", "Analytics"],
#     "Media": ["Media", "Entertainment", "Broadcasting"],
#     "Medical Devices": ["Medical Devices", "Healthcare"],
#     "Metals & Mining": ["Metals", "Mining", "Mining Equipment"],
#     "Mining": ["Mining"],
#     "Motorcycle & Scooter": ["Motorcycle", "Scooter", "Automotive"],
#     "Multimedia": ["Multimedia", "Media", "Digital"],
#     "Museums & Galleries": ["Museums", "Culture"],
#     "Oil & Gas": ["Oil", "Gas", "Energy"],
#     "Oil Exploration": ["Oil Exploration", "Energy", "Extraction"],
#     "Oil Refineries": ["Oil Refineries"],
#     "Optical Instruments": ["Optical Instruments"],
#     "Organic Chemicals": ["Organic Chemicals", "Pharmaceutical", "Agriculture"],
#     "Packaging": ["Packaging"],
#     "Paints & Coatings": ["Paints", "Coatings"],
#     "Paper & Paper Products": ["Paper", "Products", "Packaging"],
#     "Petroleum Products": ["Petroleum", "Fuel"],
#     "Pharmaceuticals": ["Pharmaceuticals", "Medicine", "Healthcare"],
#     "Plastic": ["Plastic", "Materials", "Products"],
#     "Plastics Products": ["Plastic Products"],
#     "Power Generation": ["Power Generation", "Energy", "Electricity"],
#     "Power Transmission": ["Power Transmission", "Electricity", "Energy"],
#     "Printing & Publishing": ["Printing", "Publishing", "Media"],
#     "Railways": ["Railways"],
#     "Real Estate": ["Real Estate", "Property", "Housing"],
#     "Recycling": ["Recycling", "Waste", "Sustainability"],
#     "Renewable Energy": ["Renewable Energy", "Sustainable", "Green"],
#     "Resins & Adhesives": ["Resins", "Adhesives"],
#     "Retail": ["Retail", "Shopping", "Store"],
#     "Rubber Products": ["Rubber", "Rubber Products"],
#     "Shipping": ["Shipping", "Transport"],
#     "Steel": ["Steel"],
#     "Telecommunication": ["Telecommunication", "Mobile", "Communication"],
#     "Textiles & Apparel": ["Textiles", "Clothing", "Fashion"],
#     "Tires & Rubber": ["Tires", "Rubber"],
#     "Toys & Games": ["Toys", "Games"],
#     "Trading": ["Trading"],
#     "Transportation": ["Transportation","Shipping"],
#     "Utilities": ["Utilities", "Energy", "Water"],
#     "Vending": ["Vending"],
#     "Wires & Cables": ["Wires", "Cables"],
#     "Wood Products": ["Wood", "Timber"],
#     "Zinc": ["Zinc"]
# }

industry_keywords = {
    "All Engineering & Electronics": ["Electronics", "Electronic", "Circuit", "Machinery", "Industrial Machinery", "Computers - Software & Consulting", "Computers Hardware & Equipments", "Industrial Gases", "Heavy Electrical Equipment"],
    "Beverages (excluding Tea & Coffee) & Tobacco": ["Food", "Beverages", "Drinks", "Restaurant", "Dining", "Catering", "Breweries & Distilleries", "Cigarettes & Tobacco Products", "Alcoholic Beverages"],
    "Iron and Steel": ["Iron", "Steel", "Metals", "Steel Products", "Iron Products", "Ferrous Metals", "Non-ferrous Metals"],
    "Other Metal and Metal Products": ["Aluminium", "Copper", "Zinc", "Ferro & Silica Manganese", "Copper", "Metalworking", "Castings & Forgings"],
    "Cement": ["Cement", "Building Materials", "Cement Products", "Construction Materials", "Cement", "Construction", "Cement"],
    "Chemical & Chemical Products": ["Chemicals", "Chemical", "Pharmaceutical", "Chemical Plant", "Commodity Chemicals", "Organic Chemicals", "Fertilizers", "Lubricants & Oils", "Chemicals - Basic Chemicals", "Chemicals - Petrochemicals", "Chemicals - Specialty Chemicals"],
    "Construction": ["Building Construction Material","Construction", "Building", "Architecture", "Infrastructure", "Contractor", "Civil Construction", "Construction Vehicles", "Construction Materials", "Construction Equipment"],
    "Food Processing (excluding Sugar)": ["Food", "Agricultural", "Farming", "Dairy Products", "Fertilizers", "Food Processing", "Catering", "Basmati Rice", "Non-Basmati Rice", "Edible Oil", "Dairy"],
    "Glass & Glassware": ["Glass", "Consumer Products", "Industrial Glass", "Glass - Consumer", "Glass - Industrial"],
    "Gems & Jewellery": ["Gems", "Jewellery", "Watches", "Jewellery"],
    "Infrastructure - Power": ["Power Generation", "Electricity", "Energy", "Solar", "Power Transmission", "Power Utilities", "Power", "Renewable Energy", "Electric Vehicles"],
    "Infrastructure – Road & Transport": ["Road", "Transport", "Infrastructure", "Railways", "Transportation", "Shipping", "Ports", "Roads & Highways", "Airport Infrastructure", "Ports", "Ship Breaking", "Logistics - Road"],
    "Infrastructure – Social": ["Healthcare", "Education", "Social Infrastructure", "Hospital", "Healthcare", "Healthcare", "Hospitals"],
    "Infrastructure - Telecom": ["Telecom", "Telecommunication", "Broadband", "Mobile", "Network", "Communication", "Telecom Services", "Telecom Tower"],
    "Leather & Leather Products": ["Leather", "Leather Products"],
    "Mining and Quarrying": ["Mining", "Coal", "Quarry", "Metals & Mining", "Iron & Steel", "Mining & Quarrying", "Critical Minerals"],
    "NBFC & BFSI": ["Finance","BFSI", "Financial", "Banking", "Investment", "Capital", "Credit", "Accounting", "Bank", "Financial Institution", "Financial Products Distributor", "NBFC – Infrastructure", "NBFC – Retail & Commercial Finance", "Small NBFCs", "Small Finance Banks", "Banking", "Financial Markets & Banking Update","Asset-Backed Security", "Brokerages", "Credit Quality Trends", "Life Insurance", "General Insurance", "Market Update", "State Government Finance", "Corporate sector", "Mortgage-Backed Security", "Economic Outlook & Macro Trends", "Outlook FY2025","Affordable Housing Finance"],
    "Paper": ["Paper", "Paper Products", "Packaging", "Paper Manufacturing"],
    "Petroleum": ["Petroleum", "Oil", "Fuel", "Gas", "Oil Exploration", "Oil Refineries", "Oil & Gas", "Refining & Marketing"],
    "Plastic & Plastic Products": ["Plastic", "Plastic Products", "Materials"],
    "Rubber & Rubber Products": ["Rubber", "Rubber Products", "Tyres", "Automobile"],
    "Sugar": ["Sugar", "Agricultural Products", "Food Processing", "Sugar"],
    "Textile": ["Textiles", "Clothing", "Fashion", "Apparel", "Garments", "Textiles", "Garments & Apparels", "Cotton & Manmade Yarns", "Apparel & Fabric"],
    "Tourism": ["Tourism", "Hotel", "Resort", "Hospitality", "Travel", "Vacation", "Tourist", "Hotels"],
    "Vehicle, Vehicle Parts & Transport Equipment": ["Automotive", "Car", "Vehicle", "Motor", "Automobile", "Motorcycle", "Scooter", "Auto Components & Equipments", "Commercial Vehicles", "Transport Equipment", "Shipping", "Passenger Vehicles", "Tractors", "Two Wheelers", "Auto Components"],
    "Wood & Wood Products": ["Wood", "Timber", "Wood Products", "Furniture", "Woodworking"],
    "Real Estate": ["Real Estate", "Construction", "Property", "Housing", "Housing Finance Companies", "Real Estate", "Housing Finance Statistics"],
    "Others": ["Multiplex Industry", "Others", "Company Update", "ICRA Market Outreach", "Market Update", "Cross-sectoral trends and outlook", "Print Media", "Data Centres", "Defence", "Cashew", "Buffalo Meat", "Bulk Tea", "Dairy", "Seeds"],
	"Govt. & Politics" :["Tax","Income Tax","GST"]
}

# Function to determine the industry based on headline and description
def find_industry(headline, description, keywords):
    if headline:
        headline = headline.title()
    if description:
        description = description.title()

    text = (headline + " " + (description or "")).title()  # Combine and normalize text
    industry_scores = {industry: 0 for industry in keywords}  # Initialize scores

    for industry, phrases in keywords.items():
        for phrase in phrases:
            if phrase.title() in text:  # Match phrase in text
                industry_scores[industry] += text.count(phrase.title())  # Count occurrences

    # Return the highest scoring industry, if any
    max_industry = max(industry_scores, key=industry_scores.get)
    return max_industry if industry_scores[max_industry] > 0 else "Other"