def get_basic_financials_headers():
    return {
        "CIN": None,
        "Year": None,
        "Pan of Company": None,
        "Company Name": None,
        "Website": None,
        "Telephone": None,
        "If company has Share Capital": None,
        "CIN of Registrar/Transfer Agent": None,
        "Name of Registrar/Transfer Agent": None,
        "Address of Registrar/Transfer Agent": None,
        "Financial Year Start Date": None,
        "Financial Year End Date": None,
        "No. of Principal Businesses": None,
        "Entity Structure No.": None,
        "TotalEquitySharesAuthorisationCapital": None,
        "TotalEquitySharesIssuedCapital": None,
        "TotalEquitySharesSubscribedCapital": None,
        "TotalEquitySharesPaidUpCapital": None,
        "TotalEquitySharesAuthorisationCapitalValue": None,
        "TotalEquitySharesIssuedCapitalValue": None,
        "TotalEquitySharesSubscribedCapitalValue": None,
        "TotalEquitySharesPaidUpCapitalValue": None,
        "Number of classesEquity": None,
        "TotalPreferenceSharesAuthorisationCapital": None,
        "TotalPreferenceSharesIssuedCapital": None,
        "TotalPreferenceSharesSubscribedCapital": None,
        "TotalPreferenceSharesPaidUpCapital": None,
        "TotalPreferenceSharesAuthorisationCapitalValue": None,
        "TotalPreferenceSharesIssuedCapitalValue": None,
        "TotalPreferenceSharesSubscribedCapitalValue": None,
        "TotalPreferenceSharesPaidUpCapitalValue": None,
        "Number of classes Preference": None,
        "Total Value Unclassified Shares": None,
        "Break Up PC - No. of Shares at BoY": None,
        "Break Up PC - Total Nominal Amount at BoY": None,
        "Break Up PC - Total PC Amount at BoY": None,
        "Break Up PC - Total Premium at BoY": None,
        "Break Up PC - Inc No. of Shares at DY": None,
        "Break Up PC - Inc Total Nominal Amount at DY": None,
        "Break Up PC - Inc Total PC Amount at DY": None,
        "Break Up PC - Inc Total Premium at DY": None,
        "Break Up PC - PI No. of Shares at DY": None,
        "Break Up PC - PI Total Nominal Amount at DY": None,
        "Break Up PC - PI Total PC Amount at DY": None,
        "Break Up PC - PI Total Premium at DY": None,
        "Break Up PC - RI No. of Shares at DY": None,
        "Break Up PC - RI Total Nominal Amount at DY": None,
        "Break Up PC - RI Total PC Amount at DY": None,
        "Break Up PC - RI Total Premium at DY": None,
        "Break Up PC - BI No. of Shares at DY": None,
        "Break Up PC - BI Total Nominal Amount at DY": None,
        "Break Up PC - BI Total PC Amount at DY": None,
        "Break Up PC - BI Total Premium at DY": None,
        "Break Up PC - PP No. of Shares at DY": None,
        "Break Up PC - PP Total Nominal Amount at DY": None,
        "Break Up PC - PP Total PC Amount at DY": None,
        "Break Up PC - PP Total Premium at DY": None,
        "Break Up PC - ESOP No. of Shares at DY": None,
        "Break Up PC - ESOP Total Nominal Amount at DY": None,
        "Break Up PC - ESOP Total PC Amount at DY": None,
        "Break Up PC - ESOP Total Premium at DY": None,
        "Break Up PC - SE No. of Shares at DY": None,
        "Break Up PC - SE Total Nominal Amount at DY": None,
        "Break Up PC - SE Total PC Amount at DY": None,
        "Break Up PC - SE Total Premium at DY": None,
        "Break Up PC - CPS No. of Shares at DY": None,
        "Break Up PC - CPS Total Nominal Amount at DY": None,
        "Break Up PC - CPS Total PC Amount at DY": None,
        "Break Up PC - CPS Total Premium at DY": None,
        "Break Up PC - CD No. of Shares at DY": None,
        "Break Up PC - CD Total Nominal Amount at DY": None,
        "Break Up PC - CD Total PC Amount at DY": None,
        "Break Up PC - CD Total Premium at DY": None,
        "Break Up PC - DR No. of Shares at DY": None,
        "Break Up PC - DR Total Nominal Amount at DY": None,
        "Break Up PC - DR Total PC Amount at DY": None,
        "Break Up PC - DR Total Premium at DY": None,
        "Break Up PC - OTH No. of Shares at DY": None,
        "Break Up PC - OTH Total Nominal Amount at DY": None,
        "Break Up PC - OTH Total PC Amount at DY": None,
        "Break Up PC - OTH Total Premium at DY": None,
        "Break Up PC - Dec. No. of Shares at DY": None,
        "Break Up PC - Dec. Total Nominal Amount at DY": None,
        "Break Up PC - Dec. Total PC Amount at DY": None,
        "Break Up PC - Dec. Total Premium at DY": None,
        "Break Up PC - BB No. of Shares at DY": None,
        "Break Up PC - BB Total Nominal Amount at DY": None,
        "Break Up PC - BB Total PC Amount at DY": None,
        "Break Up PC - BB Total Premium at DY": None,
        "Break Up PC - SF No. of Shares at DY": None,
        "Break Up PC - SF Total Nominal Amount at DY": None,
        "Break Up PC - SF Total PC Amount at DY": None,
        "Break Up PC - SF Total Premium at DY": None,
        "Break Up PC - RSC No. of Shares at DY": None,
        "Break Up PC - RSC Total Nominal Amount at DY": None,
        "Break Up PC - RSC Total PC Amount at DY": None,
        "Break Up PC - RSC Total Premium at DY": None,
        "Break Up PC - Dec. Oth No. of Shares at DY": None,
        "Break Up PC - Dec. Oth Total Nominal Amount at DY": None,
        "Break Up PC - Dec. Oth Total PC Amount at DY": None,
        "Break Up PC - Dec. Oth Total Premium at DY": None,
        "Break Up PC - No. of Shares at EoY": None,
        "Break Up PC - Total Nominal Amount at EoY": None,
        "Break Up PC - Total PC Amount at EoY": None,
        "Break Up PC - Total Premium at EoY": None,
        "Break Up PC - No. of Pref Shares at BoY": None,
        "Break Up PC - Total Pref Nominal Amount at BoY": None,
        "Break Up PC - Total Pref PC Amount at BoY": None,
        "Break Up PC - Total Pref Premium at BoY": None,
        "Break Up PC - Inc No. of Pref Shares at DY": None,
        "Break Up PC - Inc Total Pref Nominal Amount at DY": None,
        "Break Up PC - Inc Total Pref PC Amount at DY": None,
        "Break Up PC - Inc Total Pref Premium at DY": None,
        "Break Up PC - IS No. of Pref Shares at DY": None,
        "Break Up PC - IS Total Pref Nominal Amount at DY": None,
        "Break Up PC - IS Total Pref PC Amount at DY": None,
        "Break Up PC - IS Total Pref Premium at DY": None,
        "Break Up PC - RS No. of Pref Shares at DY": None,
        "Break Up PC - RS Total Pref Nominal Amount at DY": None,
        "Break Up PC - RS Total Pref PC Amount at DY": None,
        "Break Up PC - RS Total Pref Premium at DY": None,
        "Break Up PC - Oth No. of Pref Shares at DY": None,
        "Break Up PC - Oth Total Pref Nominal Amount at DY": None,
        "Break Up PC - Oth Total Pref PC Amount at DY": None,
        "Break Up PC - Oth Total Pref Premium at DY": None,
        "Break Up PC - Dec. No. of Pref Shares at DY": None,
        "Break Up PC - Dec. Total Pref Nominal Amount at DY": None,
        "Break Up PC - Dec. Total Pref PC Amount at DY": None,
        "Break Up PC - Dec. Total Pref Premium at DY": None,
        "Break Up PC - RD No. of Pref Shares at DY": None,
        "Break Up PC - RD Total Pref Nominal Amount at DY": None,
        "Break Up PC - RD Total Pref PC Amount at DY": None,
        "Break Up PC - RD Total Pref Premium at DY": None,
        "Break Up PC - SF No. of Pref Shares at DY": None,
        "Break Up PC - SF Total Pref Nominal Amount at DY": None,
        "Break Up PC - SF Total Pref PC Amount at DY": None,
        "Break Up PC - SF Total Pref Premium at DY": None,
        "Break Up PC - RSC No. of Pref Shares at DY": None,
        "Break Up PC - RSC Total Pref Nominal Amount at DY": None,
        "Break Up PC - RSC Total Pref PC Amount at DY": None,
        "Break Up PC - RSC Total Pref Premium at DY": None,
        "Break Up PC - Dec. Oth No. of Pref Shares at DY": None,
        "Break Up PC - Dec. Oth Total Pref Nominal Amount at DY": None,
        "Break Up PC - Dec. Oth Total Pref PC Amount at DY": None,
        "Break Up PC - Dec. Oth Total Pref Premium at DY": None,
        "Break Up PC - No. of Pref Shares at EoY": None,
        "Break Up PC - Total Pref Nominal Amount at EoY": None,
        "Break Up PC - Total Pref PC Amount at EoY": None,
        "Break Up PC - Total Pref Premium at EoY": None,
        "NoOfNonConvertibleDebentures": None,
        "AmtPerNonConvertibleDebenture": None,
        "Total Value NCD": None,
        "NoOfPartlyConvertibleDebenture": None,
        "AmtPerPartlyConvertibleDebenture": None,
        "Total Value PCD": None,
        "NoOfFullyConvertibleDebenture": None,
        "AmtPerFullyConvertibleDebenture": None,
        "Total Value FCD": None,
        "Indebtness Secured Loans": None,
        "Indebtness Unsecured Loans": None,
        "Deposits": None,
        "Total No. of Units": None,
        "IndebtednessOfCompany": None,
        "NCD BoY": None,
        "NCD Inc DY": None,
        "NCD Dec DY": None,
        "NCD EoY": None,
        "PCD BoY": None,
        "PCD Inc DY": None,
        "PCD Dec DY": None,
        "PCD EoY": None,
        "FCD BoY": None,
        "FCD Inc DY": None,
        "FCD Dec DY": None,
        "FCD EoY": None,
        "No. of Other Securities": None,
        "Total No. of Security": None,
        "Total Nominal Value": None,
        "Total Paid Up Value": None,
        "Turnover": None,
        "Net Worth": None,
        "No. of Promoters": None,
        "Promoter Eq NoS Indian": None,
        "Promoter Eq % Indian": None,
        "Promoter Eq NoS NRI": None,
        "Promoter Eq % NRI": None,
        "Promoter Eq NoS Foreign National": None,
        "Promoter Eq % Foreign National": None,
        "Promoter Eq NoS Central Gov.": None,
        "Promoter Eq % Central Gov.": None,
        "Promoter Eq NoS State Gov.": None,
        "Promoter Eq % State Gov.": None,
        "Promoter Eq NoS Gov Comp.": None,
        "Promoter Eq % Gov Comp.": None,
        "Promoter Eq NoS Insurance": None,
        "Promoter Eq %Insurance": None,
        "Promoter Eq NoS Banks": None,
        "Promoter Eq % Banks": None,
        "Promoter Eq NoS Fin Inst.": None,
        "Promoter Eq % Fin Inst.": None,
        "Promoter Eq NoS Foreign Inst.": None,
        "Promoter Eq % Foreign Inst.": None,
        "Promoter Eq NoS Mutual Funds": None,
        "Promoter Eq % Mutual Funds": None,
        "Promoter Eq NoS Venture Capital": None,
        "Promoter Eq % Venture Capital": None,
        "Promoter Eq NoS Body Corporate": None,
        "Promoter Eq % Body Corporate": None,
        "Promoter Eq NoS Others": None,
        "Promoter Eq % Others": None,
        "Promoter Eq NoS Total": None,
        "Promoter Eq % Total": None,
        "Promoter Pref NoS Indian": None,
        "Promoter Pref % Indian": None,
        "Promoter Pref NoS NRI": None,
        "Promoter Pref % NRI": None,
        "Promoter Pref NoS Foreign National": None,
        "Promoter Pref % Foreign National": None,
        "Promoter Pref NoS Central Gov.": None,
        "Promoter Pref % Central Gov.": None,
        "Promoter Pref NoS State Gov.": None,
        "Promoter Pref % State Gov.": None,
        "Promoter Pref NoS Gov Comp.": None,
        "Promoter Pref % Gov Comp.": None,
        "Promoter Pref NoS Insurance": None,
        "Promoter Pref %Insurance": None,
        "Promoter Pref NoS Banks": None,
        "Promoter Pref % Banks": None,
        "Promoter Pref NoS Fin Inst.": None,
        "Promoter Pref % Fin Inst.": None,
        "Promoter Pref NoS Foreign Inst.": None,
        "Promoter Pref % Foreign Inst.": None,
        "Promoter Pref NoS Mutual Funds": None,
        "Promoter Pref % Mutual Funds": None,
        "Promoter Pref NoS Venture Capital": None,
        "Promoter Pref % Venture Capital": None,
        "Promoter Pref NoS Body Corporate": None,
        "Promoter Pref % Body Corporate": None,
        "Promoter Pref NoS Others": None,
        "Promoter Pref % Others": None,
        "Promoter Pref NoS Total": None,
        "Promoter Pref % Total": None,
        "No. of Public Promoters": None,
        "Pub Promoter Eq NoS Indian": None,
        "Pub Promoter Eq % Indian": None,
        "Pub Promoter Eq NoS NRI": None,
        "Pub Promoter Eq % NRI": None,
        "Pub Promoter Eq NoS Foreign National": None,
        "Pub Promoter Eq % Foreign National": None,
        "Pub Promoter Eq NoS Central Gov.": None,
        "Pub Promoter Eq % Central Gov.": None,
        "Pub Promoter Eq NoS State Gov.": None,
        "Pub Promoter Eq % State Gov.": None,
        "Pub Promoter Eq NoS Gov Comp.": None,
        "Pub Promoter Eq % Gov Comp.": None,
        "Pub Promoter Eq NoS Insurance": None,
        "Pub Promoter Eq %Insurance": None,
        "Pub Promoter Eq NoS Banks": None,
        "Pub Promoter Eq % Banks": None,
        "Pub Promoter Eq NoS Fin Inst.": None,
        "Pub Promoter Eq % Fin Inst.": None,
        "Pub Promoter Eq NoS Foreign Inst.": None,
        "Pub Promoter Eq % Foreign Inst.": None,
        "Pub Promoter Eq NoS Mutual Funds": None,
        "Pub Promoter Eq % Mutual Funds": None,
        "Pub Promoter Eq NoS Venture Capital": None,
        "Pub Promoter Eq % Venture Capital": None,
        "Pub Promoter Eq NoS Body Corporate": None,
        "Pub Promoter Eq % Body Corporate": None,
        "Pub Promoter Eq NoS Others": None,
        "Pub Promoter Eq % Others": None,
        "Pub Promoter Eq NoS Total": None,
        "Pub Promoter Eq % Total": None,
        "Pub Promoter Pref NoS Indian": None,
        "Pub Promoter Pref % Indian": None,
        "Pub Promoter Pref NoS NRI": None,
        "Pub Promoter Pref % NRI": None,
        "Pub Promoter Pref NoS Foreign National": None,
        "Pub Promoter Pref % Foreign National": None,
        "Pub Promoter Pref NoS Central Gov.": None,
        "Pub Promoter Pref % Central Gov.": None,
        "Pub Promoter Pref NoS State Gov.": None,
        "Pub Promoter Pref % State Gov.": None,
        "Pub Promoter Pref NoS Gov Comp.": None,
        "Pub Promoter Pref % Gov Comp.": None,
        "Pub Promoter Pref NoS Insurance": None,
        "Pub Promoter Pref %Insurance": None,
        "Pub Promoter Pref NoS Banks": None,
        "Pub Promoter Pref % Banks": None,
        "Pub Promoter Pref NoS Fin Inst.": None,
        "Pub Promoter Pref % Fin Inst.": None,
        "Pub Promoter Pref NoS Foreign Inst.": None,
        "Pub Promoter Pref % Foreign Inst.": None,
        "Pub Promoter Pref NoS Mutual Funds": None,
        "Pub Promoter Pref % Mutual Funds": None,
        "Pub Promoter Pref NoS Venture Capital": None,
        "Pub Promoter Pref % Venture Capital": None,
        "Pub Promoter Pref NoS Body Corporate": None,
        "Pub Promoter Pref % Body Corporate": None,
        "Pub Promoter Pref NoS Others": None,
        "Pub Promoter Pref % Others": None,
        "Pub Promoter Pref NoS Total": None,
        "Pub Promoter Pref % Total": None,
        "Total Number of Shareholders Non Promoters": None,
        "Total Shareholders": None,
        "No. of Promoters BoY": None,
        "No. of Promoters Added": None,
        "No. of Promoters Cessation": None,
        "No. of Promoters EoY": None,
        "No. of Members BoY": None,
        "No. of Members Added": None,
        "No. of Members Cessation": None,
        "No. of Members EoY": None,
        "No. of Debenture Holders BoY": None,
        "No. of Debenture Holders Added": None,
        "No. of Debenture Holders Cessation": None,
        "No. of Debenture Holders EoY": None,
        "No. of Exec Director (Promoter)": None,
        "No. of Exec Director (Non -Promoter)": None,
        "No. of Ind. Exec Director (Non -Promoter)": None,
        "No. of Non Ind. Exec Director (Non -Promoter)": None,
        "No. of Nominee Exec Director": None,
        "No. of Nominee Exec Director (Banks& FII)": None,
        "No. of Nominee Exec Director (Investing Insitutions)": None,
        "No. of Nominee Exec Director (Govt.)": None,
        "No. of Nominee Exec Director (Small Share Holders)": None,
        "No. of Nominee Exec Director (Others)": None,
        "No. of Nominee Exec Director (Total)": None,
        "No. of Non-Exec Director (Promoter)": None,
        "No. of Non-Exec Director (Non -Promoter)": None,
        "No. of Ind. Non-Exec Director (Non -Promoter)": None,
        "No. of Non Ind. Non-Exec Director (Non -Promoter)": None,
        "No. of Nominee Non-Exec Director": None,
        "No. of Nominee Non-Exec Director (Banks& FII)": None,
        "No. of Nominee Non-Exec Director (Investing Insitutions)": None,
        "No. of Nominee Non-Exec Director (Govt.)": None,
        "No. of Nominee Non-Exec Director (Small Share Holders)": None,
        "No. of Nominee Non-Exec Director (Others)": None,
        "No. of Nominee Non-Exec Director (Total)": None,
        "% shares by Exec Director (Promoter)": None,
        "% shares by Exec Director (Non -Promoter)": None,
        "% shares by Ind. Exec Director (Non -Promoter)": None,
        "% shares by Non Ind. Exec Director (Non -Promoter)": None,
        "% shares by Nominee Exec Director": None,
        "% shares by Nominee Exec Director (Banks& FII)": None,
        "% shares by Nominee Exec Director (Investing Insitutions)": None,
        "% shares by Nominee Exec Director (Govt.)": None,
        "% shares by Nominee Exec Director (Small Share Holders)": None,
        "% shares by Nominee Exec Director (Others)": None,
        "% shares by Nominee Exec Director (Total)": None,
        "% shares by Non-Exec Director (Promoter)": None,
        "% shares by Non-Exec Director (Non -Promoter)": None,
        "% shares by Ind. Non-Exec Director (Non -Promoter)": None,
        "% shares by Non Ind. Non-Exec Director (Non -Promoter)": None,
        "% shares by Nominee Non-Exec Director": None,
        "% shares by Nominee Non-Exec Director (Banks& FII)": None,
        "% shares by Nominee Non-Exec Director (Investing Insitutions)": None,
        "% shares by Nominee Non-Exec Director (Govt.)": None,
        "% shares by Nominee Non-Exec Director (Small Share Holders)": None,
        "% shares by Nominee Non-Exec Director (Others)": None,
        "% shares by Nominee Non-Exec Director (Total)": None
    }


